### ISSUE TITLE
Реалізувати функціонал для локального збереження HTML

### ISSUE THREAD

**Issue by ReenExe** [UkraineProgrammersDating/DOUDatingAnalyzer#2]
Щоб уникнути тривалої відповіді від серверу будемо зберігати локально та далі використовувати локальну копію

**Comment by ReenExe** [comment]
Створити команду в Symfony http://symfony.com/doc/current/bundles/SensioGeneratorBundle/commands/generate_command.html
```sh
php bin/console generate:command
```

**Comment by ReenExe** [comment]
Використання стандартної папки для збереження HTML
http://stackoverflow.com/questions/31686714/how-to-get-cache-directory-from-a-service-this-container-getparameterkerne
```yaml
services:
    cache_langue:
        class: MySite\BlogBundle\Services\mycache
        arguments: ["%kernel.cache_dir%"]
```
